install:
  - cmd: >-
      mkdir c:\installers

      mkdir c:\temp

      set INCLUDE=c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include;c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include

      set LIB=c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\lib\amd64;c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\lib\x64

      set PATH=c:\Program Files (x86)\NSIS;c:\msys64\usr\bin;c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64;c:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE;c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\bin\x64;c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\bin;%PATH%

      set MSYSTEM=MINGW32

      git clone --depth=1 https://github.com/VirtualGL/buildscripts.git c:/buildscripts

build_script:
  - cmd: >-
      bash c:/buildscripts/buildvgl -r file://%CD:\=/% -b /c/vgl.nightly %APPVEYOR_REPO_BRANCH% -v

      move c:\vgl.nightly\files\*.tar.gz .

      move c:\vgl.nightly\files\*.exe .

      move c:\vgl.nightly\log-windows.txt .

artifacts:
  - path: '*.tar.gz'
    name: Source tarball

  - path: '*.exe'
    name: VirtualGL Utils

  - path: 'log-windows.txt'
    name: Build log

test: off

deploy: off
